###########
# Testing #
###########
stages:
  - build
  - linting
  - perfs # CI
  - docs
  - deploy

job:build:pythonEnv:
  stage: build
  tags:
    - unix
    - test
    - calcul
  script:
    - '/usr/bin/python3 -m venv /home/gitlab-runner/.automl_venv'
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - 'pip install -r requirements.txt'
  # artifacts:
  #   expose_as: 'Python virtual env'
  #   expire_in: 2h
  #   paths: 
  #     - .venv

job:linting:PyLint:
  stage: linting
  tags:
    - unix
    - test
    - calcul
  allow_failure: true
  script:
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - 'pylint --rcfile=.pylintrc ./src/automed'

job:test:unit:
  stage: perfs
  tags:
    - unix
    - test
    - calcul
  except:
    - main
  script:
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - 'pip install -r requirements.txt'
    - 'python3 ./tests/tests.py unit'

# job:test:integration:
#   stage: test
#   tags:
#     - unix
#     - test
#   script:
#     # - 'cp /home/gitlab-runner/ehop_toolbox_credentials.yml ./credentials.yml' # Example of a way to get credentials
#     - 'mkdir ./data'
#     - 'source ./.venv/bin/activate'
#     - 'python3 ./tests/tests.py integration'
#     # - 'rm ./credentials.yml' # Do forget to delete credentials

# Uncomment et complet below to enable CD
# job:deploy:
#   stage: deploy
#   tags:
#     - <HERE> # Add tag here. Tag will be useful to select gitlab-runner
#   script:
#     - <HERE> # Add shell command here
#   only:
#     - main # Deploy only after push on the main branch
    

###################
## PERFORMANCES  ##
###################

job:perfs:compute:
  stage: perfs
  timeout: 24h
  tags:
    - unix
    - calcul
  only:
    - main
  script:
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - 'if [ -e "./src/perf_logger/tests_data/history.log" ]; then rm ./src/perf_logger/tests_data/history.log ;fi'
    - 'if [ -e "/home/gitlab-runner/automl_history.log" ]; then cp /home/gitlab-runner/automl_history.log ./src/perf_logger/tests_data/history.log ;fi'
    - cp -R /home/gitlab-runner/dont_push /home/gitlab-runner/builds/w-N4hyQH/0/DataScience/automl/src/perf_logger/tests_data/
    - 'python3 src/perf_logger/perf_logger.py $CI_COMMIT_SHORT_SHA' # Compute perfs
    - 'python3 src/perf_logger/perf_comparator.py' # Compute perfs
    - 'if [ -e "/home/gitlab-runner/automl_history.log.old" ]; then rm /home/gitlab-runner/automl_history.log.old ;fi'
    - 'if [ -e "/home/gitlab-runner/automl_history.log" ]; then mv /home/gitlab-runner/automl_history.log /home/gitlab-runner/automl_history.log.old ;fi'
    - 'cp ./src/perf_logger/tests_data/history.log /home/gitlab-runner/automl_history.log'
  artifacts:
    expose_as: 'Compute performances of AutoMed'
    paths:
      - docs
      - ./src/perf_logger/tests_data/history.log


job:perfs:compute_stages:
  stage: perfs
  timeout: 24h
  tags:
    - unix
    - calcul
  only:
    - rm-stages
  script:
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - cp -R /home/gitlab-runner/dont_push /home/gitlab-runner/builds/w-N4hyQH/0/DataScience/automl/src/perf_logger/tests_data/
    - 'python3 src/perf_logger/perf_logger.py $CI_COMMIT_SHORT_SHA' # Compute perfs
    - 'python3 src/perf_logger/perf_comparator.py' # Compute perfs
    - 'if [ -e "/home/gitlab-runner/automl_stage_history.log" ]; then rm /home/gitlab-runner/automl_stage_history.log ;fi'
    - 'cp ./src/perf_logger/tests_data/history.log /home/gitlab-runner/automl_stage_history.log'
  artifacts:
    expose_as: 'Compute performances of AutoMed Stages'
    paths:
      - ./src/perf_logger/tests_data/history.log

###################
## DOCUMENTATION ##
###################

job:docs:create:
  stage: docs
  tags:
    - unix
  only: 
    - main
  script:
    - 'source /home/gitlab-runner/.automl_venv/bin/activate'
    - 'python3 -m pip install mkdocs'
    - 'python3 -m mkdocs build -d public'
  artifacts:
    expose_as: 'HTML Static documentation'
    paths:
      - public

job:deploy:docs:
  stage: deploy
  tags:
    - unix
    - test
    - documentation
  only:
    - main
  script: 
    - 'if [ -d "/var/www/docs/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH" ]; then rm -r /var/www/docs/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH; fi'
    - 'mkdir -p /var/www/docs/$CI_PROJECT_NAME'
    - 'mv ./public /var/www/docs/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH'