[project]
name = "iaml"
version = "0.1.0"
authors = [
    { name="Rudy MERIEUX", email="rmerieux@chu-reims.fr" },
    { name="Robin BOURACHOT", email="rbourachot@chu-reims.fr" },
    { name="Hugo RUELLET", email="hruellet@chu-reims.fr" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: OS Independent",
]
dependencies = [
    "catboost>=1.2.7",
    "gensim>=4.3.3",
    "imbalanced-learn>=0.12.3",
    "matplotlib>=3.9.2",
    "multipledispatch>=1.0.0",
    "multiprocess>=0.70.16",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "pandas>=2.2.2",
    "rich>=13.8.1",
    "scikit-learn>=1.5.2",
    "shap",
    "tpot>=0.12.2",
    "scikit-survival>=0.23.0"
    "psutil>=6.0.0",
]

[project.optional-dependencies]
cudf = [
    "cudf-cu11>=24.8.1",
]

[project.urls]
"Homepage" = "http://docs.example.invalid/automl/main/"
"Bug Tracker" = "https://gitlab.example.invalid/DataScience/automl/-/issues"

[tool.setuptools]
package-dir = { "iaml" = "src/iaml/iaml" }

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "mkdocs>=1.6.1",
    "pylint>=3.2.7",
    "ipywidgets>=8.1.5"
]

[tool.uv.sources]
shap = { git = "https://github.com/shap/shap.git", rev = "98f0b61c0ddc41595c765f79d9cccdeb0cc608a0" }
